root_url: https://kukai-core-swift.kukai.app/
output: Documentation
swift_build_tool: xcodebuild
xcodebuild_arguments:
  - "-scheme"
  - "KukaiCoreSwift"
  - "-destination"
  - "platform=iOS Simulator,OS=17.2,name=iPhone 15"